version: 0.0
os: linux
files:
  - source: files
    destination: /root

hooks:
  AfterInstall:
    - location: scripts/import_db
      timeout: 300
      runas: root
    - location: scripts/stop_server
      timeout: 300
      runas: root
    - location: scripts/files
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
