#!/bin/bash
if [ -e /root/*_*.tgz ]; then
    date=`date +%F"-"%H"-"%M`
    data_dir=/data/drupal8
    project=$(basename /root/*_*.tgz|head -1|cut -d_ -f1)
    dirs=$(basename /root/*_*.tgz|cut -d_ -f2|cut -d. -f1)

    for dir in ${dirs}; do
        mkdir -p ${data_dir}/${dir}/${project}-${date}
        tar xvfz /root/${project}_${dir}.tgz -C ${data_dir}/${dir}/${project}-${date}
        chown -R apache:siftdigital ${data_dir}/${dir}/${project}-${date} && /
        rm -rf ${data_dir}/${dir}/${project} && /
        ln -s ${data_dir}/${dir}/${project}-${date} ${data_dir}/${dir}/${project}
    done
fi
